/*
Data types can be divided into two:

1)Primitive data types
2)Non-primitive data types(Object References)


1)Numbers - Integers, floats
2)Strings - Any data under single quote, double quote or backtick quote
3)Booleans - true or false value
4)Null - empty value or no value
5)Undefined - a declared variable without a value
6)Symbol - A unique value that can be generated by Symbol construct

Non-primitive data types in JavaScript includes:

1)Objects
2)Arrays



Note: Primitive data types are immutable(non-modifiable) data types. Once a primitive data type is created we cannot modify it.

Example  


let word = 'JavaScript'
word[0] = 'Y'        it goona show error cause string . dounle quote or backtick quote is string data type 


*/

let numOne = 3;
let numTwo = 3;

console.log(numOne == numTwo); // true

let js = "JavaScript";
let py = "Python";

console.log(js == py); // false

let lightOn = true;
let lightOff = false;

console.log(lightOn == lightOff); // false

// Non-primitive data types are modifiable or mutable. We can modify the value of non-primitive data types after it gets created

// let nums = [1,2,4]
// nums[0] = 10

// console.log(nums);   // [10. 2.4]

// let nums = [1,2,3]

// let numbers = [1, 2, 3]

// console.log(nums == numbers);   // false

// let userOne = {
//   name: "Ashish",
//   role: "teaching",
//   country: "Bharat",
// };

// let userTwo = {
//   name: "Ashish",
//   role: "teaching",
//   country: "Bharat",
// };

// let userTwo = userOne 
// console.log(userOne == userTwo);
// console.log(userTwo);



// console.log(userOne == userTwo);   // false



// note : Non-primitive data types ko value ke basis par compare nahi kar sakte. Even agar do non-primitive data types ke properties aur values same hain, tab bhi woh strictly equal (===) nahi hote.


// Numbers



let age = 35
const gravity = 9.81  // we use const for non-changing values, gravitational constant in  m/s2
let mass = 72         // mass in Kilogram
const PI = 3.14       // pi a geometrical constant

// More Examples
const boilingPoint = 100 // temperature in oC, boiling point of water which is a constant
const bodyTemp = 37      // oC average human body temperature, which is a constant

console.log(age, gravity, mass, PI, boilingPoint, bodyTemp)

